### ISSUE TITLE
difference between this and "NextJS-AntD-LESS" repo

### ISSUE THREAD

**Issue by kamilml** [mit123suki/next-ant-css#1]
Hi. Thanks for your work :)

I am starting a new project. I want to use next and antd, what is the difference between both repositories? And which one do you recommend to use?

Maybe can I contact with you? to exchange knowledge ;)

**Comment by mit123suki** [comment]
Go with this only for mainly 2 reasons, 
- It got support for css and modules out of the box so no configuration needed for this
- The Less repo depends on next-css/less plugins, which are not maintained anymore so no future updates/upgrades by next team
