### ISSUE TITLE
Difference with the updated official next-ant-example?

### ISSUE THREAD

**Issue by jericopulvera** [mit123suki/next-ant-css#3]
I would like to know the main differences between this and the official repo example.

https://github.com/zeit/next.js/tree/canary/examples/with-ant-design

Thanks!

**Comment by mit123suki** [comment]
Hi, sorry for the delayed response. there was some change in the configuration, between the 2 repos like using es6 lib for treeshaking.. (refer babelrc)

Anyway, use https://github.com/mit123suki/next-ant-setup, though it's little hacky it doesn't suffer from the ant-next-integration problems. 

This repo shows how to setup with ant without customizing the webpack. But this requires some effort for first time if you want to configure from scratch, refer readme for more details
